### ISSUE TITLE
Status coloring has strange visual when 3D model has textures

### ISSUE THREAD

**Issue by ccrowley96** [microsoft/iot-cardboard-js#389]
**Describe the bug**
When the 3D model in these scene has colors / textures, status colors appear striped / non-consitent.

**To Reproduce**
1. Go to [download ISS model](https://solarsystem.nasa.gov/resources/2378/international-space-station-3d-model/)
2. Create scene with ISS model & add status coloring visual to solar panels
3. Go to view mode & view status coloring on solar panels
4. See striped visuals on front of panels, solid visuals on back

**Expected behavior**
Solar panels show consistent status coloring

**Screenshots**
### Front of panels
![image](https://user-images.githubusercontent.com/18181049/166734156-bbe95d8f-e8ea-4e22-b6ec-f1890d0460fb.png)
### Back of panels
![image](https://user-images.githubusercontent.com/18181049/166735085-3795ff3b-04f0-4114-b055-5b36206ab6d7.png)

**Browser (please complete the following information):**
 - Chrome

**Comment by coryboyle** [comment]
This is a visual artifact called z-fighting. It looks like the mesh on one side has been highlighted, but shares the same world space as the mesh on the other side. Normally, you can't see the backside of the mesh, but we turn them on when highlighting so that highlights are visible from any camera position including from behind. I would recommend that we link both sides of the mesh to this behavior so that it includes both sides of the solar panel when highlighted.

**Comment by pasanchMSFT** [comment]
To illustrate the workaround that Cory is talking about above. Do the following in the builder experience and save the element with both back and front meshes selected.

![zfightingWorkaround](https://user-images.githubusercontent.com/55852250/206306202-a57fdd88-a0e8-4389-9b51-00ea1863c37f.gif)
